NumPy

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np #np is the alias name 

In [4]:
#convert a list -- to an array and then we use NumPy on top of that array
my_list=[1,2,3,4,5]

In [5]:
type(my_list)

list

In [6]:
my_array=np.array(my_list) #.array() will convert the list into an array

In [7]:
print(my_array)

[1 2 3 4 5]


In [9]:
type(my_array) #n dimentional array, here n=1 i.e. 1 Dimentional array

numpy.ndarray

In [10]:
#2D array or a nested array
my_list_1=[1,2,3,4,5]
my_list_2=[3,4,5,0,1]
my_list_3=[4,1,0,0,5]

new_array=np.array([my_list_1,my_list_2,my_list_3])

In [13]:
print(new_array) #2d array(matrix) with shape 3,5

[[1 2 3 4 5]
 [3 4 5 0 1]
 [4 1 0 0 5]]


In [14]:
new_array.shape #here 3 is the number of rows and 5 is the number of columns

(3, 5)

In [15]:
new_array.reshape(5,3) 

array([[1, 2, 3],
       [4, 5, 3],
       [4, 5, 0],
       [1, 4, 1],
       [0, 0, 5]])

In [16]:
new_array.reshape(5,4)

ValueError: cannot reshape array of size 15 into shape (5,4)

In [17]:
new_array.reshape(1,15)

array([[1, 2, 3, 4, 5, 3, 4, 5, 0, 1, 4, 1, 0, 0, 5]])

In [19]:
arr_new=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [21]:
print(arr_new)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [22]:
arr_new.reshape(2,2,3) 
#first param - the number of matrix we get in the o/p
#2nd and 3rd param - the shape of each matrix

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [23]:
arr_new.reshape(3,2,2) 

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [24]:
arr_new.flatten() 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [26]:
new_array.flatten() 

array([1, 2, 3, 4, 5, 3, 4, 5, 0, 1, 4, 1, 0, 0, 5])

In [27]:
a=np.array([1,2,3,4,5])

In [28]:
print(a)

[1 2 3 4 5]


In [29]:
print("add 1 to each element",a+1)
print("mul 5 to each element",a*5)
print("sub 2 from each element",a-2)
print("divide each element by 2",a/2)

add 1 to each element [2 3 4 5 6]
mul 5 to each element [ 5 10 15 20 25]
sub 2 from each element [-1  0  1  2  3]
divide each element by 2 [0.5 1.  1.5 2.  2.5]


In [30]:
new_arr=np.array([[1,5,7],[4,7,2],[3,1,9]])

In [31]:
print(new_arr)

[[1 5 7]
 [4 7 2]
 [3 1 9]]


In [33]:
print("largest element from the matrix is",new_arr.max())
print("smallest element from the matrix is",new_arr.min())
print("sum of all the element from the matrix is",new_arr.sum())

largest element from the matrix is 9
smallest element from the matrix is 1
sum of all the element from the matrix is 39


In [36]:
print("transpose of the matrix is ", new_arr.T) #T indicates we perform Transpost where rows becomes columns and vice versa

transpose of the matrix is  [[1 4 3]
 [5 7 1]
 [7 2 9]]
