NumPy

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np #np is the alias name 

In [4]:
#convert a list -- to an array and then we use NumPy on top of that array
my_list=[1,2,3,4,5]

In [5]:
type(my_list)

list

In [6]:
my_array=np.array(my_list) #.array() will convert the list into an array

In [7]:
print(my_array)

[1 2 3 4 5]


In [9]:
type(my_array) #n dimentional array, here n=1 i.e. 1 Dimentional array

numpy.ndarray

In [10]:
#2D array or a nested array
my_list_1=[1,2,3,4,5]
my_list_2=[3,4,5,0,1]
my_list_3=[4,1,0,0,5]

new_array=np.array([my_list_1,my_list_2,my_list_3])

In [13]:
print(new_array) #2d array(matrix) with shape 3,5

[[1 2 3 4 5]
 [3 4 5 0 1]
 [4 1 0 0 5]]


In [14]:
new_array.shape #here 3 is the number of rows and 5 is the number of columns

(3, 5)

In [15]:
new_array.reshape(5,3) 

array([[1, 2, 3],
       [4, 5, 3],
       [4, 5, 0],
       [1, 4, 1],
       [0, 0, 5]])

In [16]:
new_array.reshape(5,4)

ValueError: cannot reshape array of size 15 into shape (5,4)

In [17]:
new_array.reshape(1,15)

array([[1, 2, 3, 4, 5, 3, 4, 5, 0, 1, 4, 1, 0, 0, 5]])

In [19]:
arr_new=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [21]:
print(arr_new)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [22]:
arr_new.reshape(2,2,3) 
#first param - the number of matrix we get in the o/p
#2nd and 3rd param - the shape of each matrix

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [23]:
arr_new.reshape(3,2,2) 

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [24]:
arr_new.flatten() 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [26]:
new_array.flatten() 

array([1, 2, 3, 4, 5, 3, 4, 5, 0, 1, 4, 1, 0, 0, 5])

In [27]:
a=np.array([1,2,3,4,5])

In [28]:
print(a)

[1 2 3 4 5]


In [29]:
print("add 1 to each element",a+1)
print("mul 5 to each element",a*5)
print("sub 2 from each element",a-2)
print("divide each element by 2",a/2)

add 1 to each element [2 3 4 5 6]
mul 5 to each element [ 5 10 15 20 25]
sub 2 from each element [-1  0  1  2  3]
divide each element by 2 [0.5 1.  1.5 2.  2.5]


In [30]:
new_arr=np.array([[1,5,7],[4,7,2],[3,1,9]])

In [31]:
print(new_arr)

[[1 5 7]
 [4 7 2]
 [3 1 9]]


In [33]:
print("largest element from the matrix is",new_arr.max())
print("smallest element from the matrix is",new_arr.min())
print("sum of all the element from the matrix is",new_arr.sum())

largest element from the matrix is 9
smallest element from the matrix is 1
sum of all the element from the matrix is 39


In [36]:
print("transpose of the matrix is ", new_arr.T) #T indicates we perform Transpost where rows becomes columns and vice versa

transpose of the matrix is  [[1 4 3]
 [5 7 1]
 [7 2 9]]


In [3]:
mat_1=np.array([[1,2],[3,4]])
mat_2=np.array([[4,3],[2,1]])

In [6]:
print("adding the metrics together",mat_1+mat_2)

adding the metrics together [[5 5]
 [5 5]]


In [7]:
print("multiplication of metrics is",mat_1*mat_2)

multiplication of metrics is [[4 6]
 [6 4]]


In [8]:
#Principal Component Analysis in ML - we extensively make use of eigen values and eigen vectors 

In [9]:
print(np.linalg.eig(mat_1))

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


Generating numbers using NumPy

- arange()

- linspace()

- random.rand()

- random.randint()

In [10]:
np.arange(1,10) #here 10 will be exclusive and we get an output from 1 to 9 (equally spaced)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,15,2) #here 2 is the step size  

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [13]:
np.arange(0,25,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [14]:
np.linspace(1,10,50) #here 50 is the total number of o/p we need in this range and 10 is not exclusive here

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [15]:
np.linspace(1,10,100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [20]:
np.random.rand() #gives random value between 0 and 1(being exclusive)
#bydefault range is between 0-1

0.09986767546844566

In [29]:
np.random.rand(3,4) #here 3 is the number of rows and 4 is the number of columns 

array([[0.34684415, 0.80144258, 0.32241137, 0.90598224],
       [0.96546202, 0.84236137, 0.6642745 , 0.95534247],
       [0.03304905, 0.34663133, 0.0321245 , 0.95198039]])

In [32]:
np.random.rand(2,5) #here 2 is the number of rows and 5 is the number of columns

array([[0.21445384, 0.65530228, 0.12931261, 0.32762244, 0.73809195],
       [0.38471184, 0.60353451, 0.69039405, 0.54842349, 0.78679367]])

In [39]:
np.random.randint(1,20)

11

In [49]:
np.random.randint(1,20,5)

array([17,  4, 19, 16,  1])

In [46]:
np.random.rand(5)

array([0.84383391, 0.63802781, 0.84951096, 0.42128656, 0.17209532])